### ISSUE TITLE
Wine not showing up

### ISSUE THREAD

**Issue by wolf-tech07** [Botspot/wine-stuff#1]
When I get on pi apps wine just is not there I just updated it and on the update list it says it was there but I go to find it and its not there

**Comment by Botspot** [comment]
Then you must be running either 64-bit Raspberry Pi OS or Twister OS.

64-bit Wine is not supported yet, and TwisterOS includes Wine by default.

**Comment by wolf-tech07** [comment]
Dang that was fast but yeah I'm using the 64bit software it there any way to run my exe files on the 64dit software

**Comment by neofeo** [comment]
You need to add arnhf arch and install a full 32 bit userspace to run 32 bit software like box86 or wine.

**Comment by neofeo** [comment]
We may have a better and easier workaround  down the road, but it's  not up to pi apps at the moment
